[package]
name = "soft"
version = "0.1.0"
edition = "2024"
description = "The Soft programming language - bytecode VM with native interface"
authors = ["Soft Team"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
